### ISSUE TITLE
Estuary skin for iptv record issue

### ISSUE THREAD

**Issue by Rvhalewyn** [tbrek/plugin.video.iptv.recorder#7]
I managed to install the new version for Kodi 19.
But I cannot install the special skin, getting a Webserver verification error. Windows 10.

**Comment by Rvhalewyn** [comment]
I don't get the error when I change Language to English, but that's not really a solution.
But nothing happens, and I get this log, photo 3
https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0

**Comment by tbrek** [comment]
Does you IPTV provider support archive feature?

**Comment by Rvhalewyn** [comment]
It is still not clear to me if Archive Downloader is a successor for IPTV Recorder, or a different project. If it's more or less the same, I miss certain fields like External xmltv url, and windows

**Comment by Rvhalewyn** [comment]
If it's a different project, I wonder why you gave up the original one, started by Primaeval. Couldn't it work any more in Kodi 19, provided you found a solution for the Estuary skin?
Especially daily and weekly programming was very useful.
