### ISSUE TITLE
Language issue in iptv recorder for matrix

### ISSUE THREAD

**Issue by Rvhalewyn** [tbrek/plugin.video.iptv.recorder#8]
Hi, I know you prefer not to continue supporting this, but I have a general language version question.
I had no problem with the Leia version. 
But now I upgraded and installed your matrix version, I get a parsing error when programming. The Dutch days of the week seem to be the problem.
I'd like to change the weekday names to Dutch in the strings.po file under English. Would that be the solution? But somehow I don't manage to copy that file in the Kodi File Manager. 'Failed to open savestate file.'
Think I'm close to a solution, so please, could you give me a hint?

**Comment by tbrek** [comment]
Can you post a log file? It might be an issue with parsing dates because the day is in diff format not just a language issue.

**Comment by Rvhalewyn** [comment]
Thanks for replying so soon.
It is language related, because I get no error when I set system language to English.

**Comment by Rvhalewyn** [comment]
Another problem comes up:
There seems to be no possibility anymore to set rules like 'record daily', or am I wrong? This possibility used to pop up by clicking underneath the special skin screen when clicking on a program in the grid.
By right clicking now, I can select 'record'. I get a confirmation, but it doesn't record. 

Actually I have some fixed programs I recorded every day/week in leia. I copied the old add-on data. But which files should I paste, and where, to get the old rules back? And would it really record? When I click Rules or Jobs now under Maintainance, I get a no-table error.

**Comment by Rvhalewyn** [comment]
I restored all Leia add-on data in the new matrix build. Now Full EPG, Rules, and Jobs are visible again. Can't test them before the first planned program on Monday.
When I click à program in Full EPG, I get a TGV-name, no such column error. 
When I click à program in the grid, I get a scheduled confirmation. But nothing happens, and I don't find it in Jobs.
