### ISSUE TITLE
I don't see any channels

### ISSUE THREAD

**Issue by robustini** [tbrek/plugin.video.iptv.recorder#9]
I'm on Kodi 19.3, IPTV Simple Client works perfectly but IPTV Recorder doesn't seem to do any scanning for available channels.
I attach the log.

[kodi.zip](https://github.com/tbrek/plugin.video.iptv.recorder/files/7918385/kodi.zip)

**Comment by tbrek** [comment]
This plugin is no longer maintained.

If you need to download/record from archive you can use this https://github.com/tbrek/tbrek-kodi-repo
